// AUTO-GENERATED curated avatar pools — the exact faces hand-picked from the
// gallery previews. Boys / girls keep separate pools so a guy never sees girl
// faces and vice-versa. To change the set, re-pick in the avatar-preview*.html
// galleries and regenerate.

export const BOY_AVATARS = [
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-3', // AD3
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-6', // AD6
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-31', // AD31
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-41', // AD41
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-47', // AD47
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-55', // AD55
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-60', // AD60
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-56', // AD56
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-2', // NO2
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-4', // NO4
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-9', // NO9
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-21', // NO21
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-17', // NO17
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-18', // NO18
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-16', // NO16
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-27', // NO27
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-33', // NO33
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-43', // NO43
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-34', // NO34
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-45', // NO45
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-52', // NO52
  'https://api.dicebear.com/7.x/micah/svg?seed=micah-3', // MI3
  'https://api.dicebear.com/7.x/micah/svg?seed=micah-20', // MI20
  'https://api.dicebear.com/7.x/micah/svg?seed=micah-52', // MI52
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-1', // LO1
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-9', // LO9
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-21', // LO21
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-28', // LO28
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-40', // LO40
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-51', // LO51
  'https://api.dicebear.com/7.x/lorelei/svg?seed=lorelei-58', // LO58
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-7&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX7
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-8&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX8
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-10&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX10
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-20&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX20
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-18&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX18
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-38&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX38
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-49&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX49
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-54&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX54
  'https://api.dicebear.com/7.x/avataaars/svg?seed=malex-60&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // BX60
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-2&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B2
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-5&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B5
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-6&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B6
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-8&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B8
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-19&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B19
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-15&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B15
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-12&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B12
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-25&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B25
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-39&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B39
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-47&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B47
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-59&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B59
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-58&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B58
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-57&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B57
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-55&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B55
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-54&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B54
  'https://api.dicebear.com/7.x/avataaars/svg?seed=male-52&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=shortFlat&top=shortRound&top=shortWaved&top=shortCurly&top=theCaesar&top=theCaesarAndSidePart&top=sides&top=frizzle&facialHairProbability=70&facialHair=beardLight&facialHair=beardMedium&facialHair=moustacheFancy&clothing=blazerAndShirt&clothing=blazerAndSweater&clothing=collarAndSweater&clothing=graphicShirt&clothing=hoodie&clothing=shirtCrewNeck&clothing=shirtVNeck&clothesColor=262e33&clothesColor=3c4f5c&clothesColor=5199e4&clothesColor=25557c&clothesColor=929598&clothesColor=65c9ff&clothesColor=b1e2ff&clothesColor=e6e6e6', // B52
];

export const GIRL_AVATARS = [
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-2', // AD2
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-8', // AD8
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-17', // AD17
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-12', // AD12
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-30', // AD30
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-8', // NO8
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-11', // NO11
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-26', // NO26
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-44', // NO44
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-40', // NO40
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-35', // NO35
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-50', // NO50
  'https://api.dicebear.com/7.x/notionists/svg?seed=notionists-56', // NO56
  'https://api.dicebear.com/7.x/adventurer/svg?seed=adventurer-16', // AD16
  'https://api.dicebear.com/7.x/micah/svg?seed=micah-31', // MI31
  'https://api.dicebear.com/7.x/micah/svg?seed=micah-34', // MI34
  'https://api.dicebear.com/7.x/micah/svg?seed=micah-38', // MI38
  'https://api.dicebear.com/7.x/avataaars/svg?seed=femalex-4&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // GX4
  'https://api.dicebear.com/7.x/avataaars/svg?seed=femalex-7&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // GX7
  'https://api.dicebear.com/7.x/avataaars/svg?seed=femalex-21&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // GX21
  'https://api.dicebear.com/7.x/avataaars/svg?seed=femalex-16&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // GX16
  'https://api.dicebear.com/7.x/avataaars/svg?seed=femalex-45&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // GX45
  'https://api.dicebear.com/7.x/avataaars/svg?seed=femalex-50&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // GX50
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-5&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G5
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-7&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G7
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-9&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G9
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-10&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G10
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-33&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G33
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-21&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G21
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-18&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G18
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-14&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G14
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-25&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G25
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-23&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G23
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-34&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G34
  'https://api.dicebear.com/7.x/avataaars/svg?seed=female-45&mouth=default&mouth=smile&mouth=twinkle&eyes=default&eyes=happy&eyes=wink&eyebrows=default&eyebrows=defaultNatural&eyebrows=raisedExcitedNatural&accessoriesProbability=0&hairColor=2c1b18&hairColor=4a312c&hairColor=724133&hairColor=a55728&hairColor=b58143&hairColor=c93305&hairColor=d6b370&top=straight01&top=straight02&top=straightAndStrand&top=bob&top=bun&top=curly&top=curvy&top=longButNotTooLong&top=miaWallace&top=bigHair&top=frida&top=fro&facialHairProbability=0', // G45
];
